# Generated by Django 4.2.7 on 2024-05-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_blog', '0002_category_alter_post_options_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature',
            field=models.BooleanField(default=False, verbose_name='В слайдере'),
        ),
    ]
